### ISSUE TITLE
The app is not working.

### ISSUE THREAD

**Issue by Ahmneo** [mansuf/zippyshare-downloader#7] opened 2021-04-08 17:39 UTC
When you try to download any zippyshare link, it gives the following output:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__main__.py", line 77, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__main__.py", line 73, in main
    custom_filename=args.filename
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__main__.py", line 25, in extract_single_urls
    result = json.dumps(z.extract_info(url, download=download, folder=folder, custom_filename=custom_filename))
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__init__.py", line 237, in extract_info
    custom_filename=custom_filename
  File "/usr/local/lib/python3.7/dist-packages/zippyshare_downloader/__init__.py", line 188, in _extract_info
    self._logger_info(f'Using directory "{os.path.join(os.getcwd(), folder)}"')
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by mansuf** [comment] 2021-04-09 04:29
Duplicate of #8

**Comment by mansuf** [comment] 2021-04-09 06:39
This issue is fixed on release [`v0.0.19`](https://github.com/mansuf/zippyshare-downloader/releases/tag/v0.0.19)

**Closed by mansuf** 2021-04-09 06:39 UTC
Labels: bug
